-- 테이블 생성 쿼리

CREATE TABLE `capstone`.`rent_price` (
  `address` CHAR(19) NULL COMMENT '토지의 고유한 위치를 지정하는 토지고유번호 \n시 + 시군구(일반구) + 읍면동 + 리 + 산 여부 + 본번 + 부번 (19자리)',
  `sido` VARCHAR(10) NULL COMMENT '시',
  `sigungu` VARCHAR(10) NULL COMMENT '시군구',
  `ilbangu` VARCHAR(10) NULL COMMENT '일반구',
  `eupmyeondong` VARCHAR(10) NULL COMMENT '읍면동',
  `ri` VARCHAR(10) NULL COMMENT '리',
  `main_num` VARCHAR(4) NULL COMMENT '본번',
  `sub_num` VARCHAR(4) NULL COMMENT '부번',
  `is_mountain` VARCHAR(1) NULL COMMENT '산 여부',
  `rent_type` VARCHAR(2) NULL COMMENT '전월세구분',
  `exclusive_area` VARCHAR(10) NULL COMMENT '전용면적(㎡)',
  `contract_date` VARCHAR(8) NULL COMMENT '계약일자',
  `deposit` INT NULL COMMENT '보증금\n',
  `rent` INT NULL COMMENT '월세',
  `previous_deposit` INT NULL COMMENT '종전계약 보증금',
  `previous_rent` INT NULL COMMENT '종전계약 월세',
  `building_name` VARCHAR(45) NULL COMMENT '건물 명',
  `road_name` VARCHAR(20) NULL COMMENT '도로명',
  `floor` INT NULL COMMENT '층',
  `construction_year` VARCHAR(10) NULL COMMENT '건축년도',
  `contract_start` VARCHAR(8) NULL COMMENT '계약 시작일\n',
  `contract_end` VARCHAR(8) NULL COMMENT '계약 종료일',
  `contract_type` INT NULL COMMENT '계약 구분( 0 : 기존, 1 : 신규, 2 : 갱신)',
  `renewal_right` INT NULL COMMENT '갱신요구권 ( 0 : 미 사용, 1 : 사용)');
